[theme]
base="light"
primaryColor="#1A73E8"
backgroundColor="#F8F9FA"
secondaryBackgroundColor="#FFFFFF"
textColor="#202124"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
